# Generated by Django 2.2.6 on 2020-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
