# Generated by Django 2.2.6 on 2020-05-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200506_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'tags'},
        ),
    ]
